POST http://localhost:3333/videos
Content-Type: application/json

{
    "title" : "Video nodeEE",
    "description" : "Primeiro vídeo",
    "duration" : 180
}

###

GET http://localhost:3333/videos

###

PUT http://localhost:3333/videos/2585b952-d78d-419a-afce-6b09bb1badba
Content-Type: application/json

{
    "title" : "Video react",
    "description" : "Segundo vídeo",
    "duration" : 190
}

###

DELETE http://localhost:3333/videos/74755778-4407-4af8-8901-a0069b3eefc9



